export const GET_TASKS = "TASKS/GET_TASKS";
export const ADD_TASK = "TASKS/ADD_TASK";
export const EDIT_TASK = "TASKS/EDIT_TASK";
export const GET_LIST_OF_PAGES = "TASKS/GET_LIST_OF_PAGES";
export const CHANGE_CURRENT_PAGE = "TASKS/CHANGE_CURRENT_PAGE";
export const GET_SORTED_TASKS = "TASKS/GET_SORTED_TASKS";
